name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Jakarta
          plugin_lines: yes
          plugin_traffic: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes  
          plugin_pagespeed_screenshot: no  
          plugin_pagespeed_url: aiptu.tk
