name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: "@classic"
          setup_community_templates: lowlighter/metrics@master:classic
          config_timezone: Asia/Jakarta
          plugin_activity: yes
          plugin_achievements: yes
          plugin_community: yes
          plugin_contributors: yes
          plugin_followup: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_lines: yes
          plugin_matrix: yes
          plugin_notable: yes
          plugin_people: yes
          plugin_quotes: yes
          plugin_repositories: yes
          plugin_reactions: yes
          plugin_repos: yes
          plugin_stars: yes
          plugin_traffic: yes
          plugin_translations: yes
